name: Build and release

on:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build-and-release:
        runs-on: ubuntu-slim
        steps:
            - uses: actions/checkout@v7

            - name: Build deps
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libreadline-dev libncurses-dev

            - uses: leafo/gh-actions-lua@v13
              with:
                  luaVersion: "5.1.5"

            - name: Setup
              run: ./fnl.sh setup

            - name: Build neowbunto.lua
              run: ./fnl.sh build

            - name: Release neowbunto.lua
              uses: softprops/action-gh-release@v3
              with:
                  tag_name: build-${{ github.run_number }}
                  name: build-${{ github.run_number }}
                  files: dist/neowbunto.lua
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
